# Rest-client stöder .env
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = http://localhost:3000
GET {{API_URL}}/notes

### Skapa ny note
POST {{API_URL}}/notes
Content-Type: application/json

{
    "note": "POST funkar!"
}

### Uppdatera note
PUT {{API_URL}}/notes/2
Content-Type: application/json

{
    "text": "Ny text!!"
}

### Delete note
DELETE {{API_URL}}/notes/3